// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DatanodesInfoProtos.proto

package dfs.common.protocol.objects;

public final class DatanodesInfoProtos {
  private DatanodesInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DatanodeIdProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string datanodeId = 1;
    boolean hasDatanodeId();
    String getDatanodeId();
  }
  public static final class DatanodeIdProto extends
      com.google.protobuf.GeneratedMessage
      implements DatanodeIdProtoOrBuilder {
    // Use DatanodeIdProto.newBuilder() to construct.
    private DatanodeIdProto(Builder builder) {
      super(builder);
    }
    private DatanodeIdProto(boolean noInit) {}
    
    private static final DatanodeIdProto defaultInstance;
    public static DatanodeIdProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DatanodeIdProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string datanodeId = 1;
    public static final int DATANODEID_FIELD_NUMBER = 1;
    private java.lang.Object datanodeId_;
    public boolean hasDatanodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDatanodeId() {
      java.lang.Object ref = datanodeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          datanodeId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDatanodeIdBytes() {
      java.lang.Object ref = datanodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        datanodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      datanodeId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDatanodeIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDatanodeIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdProto_fieldAccessorTable;
      }
      
      // Construct using dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        datanodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.getDescriptor();
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto getDefaultInstanceForType() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.getDefaultInstance();
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto build() {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto buildPartial() {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto result = new dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.datanodeId_ = datanodeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto) {
          return mergeFrom((dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto other) {
        if (other == dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.getDefaultInstance()) return this;
        if (other.hasDatanodeId()) {
          setDatanodeId(other.getDatanodeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              datanodeId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string datanodeId = 1;
      private java.lang.Object datanodeId_ = "";
      public boolean hasDatanodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDatanodeId() {
        java.lang.Object ref = datanodeId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          datanodeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDatanodeId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        datanodeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDatanodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        datanodeId_ = getDefaultInstance().getDatanodeId();
        onChanged();
        return this;
      }
      void setDatanodeId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        datanodeId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.objects.DatanodeIdProto)
    }
    
    static {
      defaultInstance = new DatanodeIdProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.objects.DatanodeIdProto)
  }
  
  public interface DatanodeIdsListProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protocol.objects.DatanodeIdProto datanodeIds = 1;
    java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> 
        getDatanodeIdsList();
    dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto getDatanodeIds(int index);
    int getDatanodeIdsCount();
    java.util.List<? extends dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder> 
        getDatanodeIdsOrBuilderList();
    dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder getDatanodeIdsOrBuilder(
        int index);
  }
  public static final class DatanodeIdsListProto extends
      com.google.protobuf.GeneratedMessage
      implements DatanodeIdsListProtoOrBuilder {
    // Use DatanodeIdsListProto.newBuilder() to construct.
    private DatanodeIdsListProto(Builder builder) {
      super(builder);
    }
    private DatanodeIdsListProto(boolean noInit) {}
    
    private static final DatanodeIdsListProto defaultInstance;
    public static DatanodeIdsListProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DatanodeIdsListProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdsListProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdsListProto_fieldAccessorTable;
    }
    
    // repeated .protocol.objects.DatanodeIdProto datanodeIds = 1;
    public static final int DATANODEIDS_FIELD_NUMBER = 1;
    private java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> datanodeIds_;
    public java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> getDatanodeIdsList() {
      return datanodeIds_;
    }
    public java.util.List<? extends dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder> 
        getDatanodeIdsOrBuilderList() {
      return datanodeIds_;
    }
    public int getDatanodeIdsCount() {
      return datanodeIds_.size();
    }
    public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto getDatanodeIds(int index) {
      return datanodeIds_.get(index);
    }
    public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder getDatanodeIdsOrBuilder(
        int index) {
      return datanodeIds_.get(index);
    }
    
    private void initFields() {
      datanodeIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < datanodeIds_.size(); i++) {
        output.writeMessage(1, datanodeIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < datanodeIds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, datanodeIds_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdsListProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.internal_static_protocol_objects_DatanodeIdsListProto_fieldAccessorTable;
      }
      
      // Construct using dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDatanodeIdsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (datanodeIdsBuilder_ == null) {
          datanodeIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          datanodeIdsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.getDescriptor();
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto getDefaultInstanceForType() {
        return dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.getDefaultInstance();
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto build() {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto buildPartial() {
        dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto result = new dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto(this);
        int from_bitField0_ = bitField0_;
        if (datanodeIdsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            datanodeIds_ = java.util.Collections.unmodifiableList(datanodeIds_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.datanodeIds_ = datanodeIds_;
        } else {
          result.datanodeIds_ = datanodeIdsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto) {
          return mergeFrom((dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto other) {
        if (other == dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.getDefaultInstance()) return this;
        if (datanodeIdsBuilder_ == null) {
          if (!other.datanodeIds_.isEmpty()) {
            if (datanodeIds_.isEmpty()) {
              datanodeIds_ = other.datanodeIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDatanodeIdsIsMutable();
              datanodeIds_.addAll(other.datanodeIds_);
            }
            onChanged();
          }
        } else {
          if (!other.datanodeIds_.isEmpty()) {
            if (datanodeIdsBuilder_.isEmpty()) {
              datanodeIdsBuilder_.dispose();
              datanodeIdsBuilder_ = null;
              datanodeIds_ = other.datanodeIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
              datanodeIdsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDatanodeIdsFieldBuilder() : null;
            } else {
              datanodeIdsBuilder_.addAllMessages(other.datanodeIds_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder subBuilder = dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDatanodeIds(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protocol.objects.DatanodeIdProto datanodeIds = 1;
      private java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> datanodeIds_ =
        java.util.Collections.emptyList();
      private void ensureDatanodeIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          datanodeIds_ = new java.util.ArrayList<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto>(datanodeIds_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder> datanodeIdsBuilder_;
      
      public java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> getDatanodeIdsList() {
        if (datanodeIdsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(datanodeIds_);
        } else {
          return datanodeIdsBuilder_.getMessageList();
        }
      }
      public int getDatanodeIdsCount() {
        if (datanodeIdsBuilder_ == null) {
          return datanodeIds_.size();
        } else {
          return datanodeIdsBuilder_.getCount();
        }
      }
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto getDatanodeIds(int index) {
        if (datanodeIdsBuilder_ == null) {
          return datanodeIds_.get(index);
        } else {
          return datanodeIdsBuilder_.getMessage(index);
        }
      }
      public Builder setDatanodeIds(
          int index, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto value) {
        if (datanodeIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatanodeIdsIsMutable();
          datanodeIds_.set(index, value);
          onChanged();
        } else {
          datanodeIdsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDatanodeIds(
          int index, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder builderForValue) {
        if (datanodeIdsBuilder_ == null) {
          ensureDatanodeIdsIsMutable();
          datanodeIds_.set(index, builderForValue.build());
          onChanged();
        } else {
          datanodeIdsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDatanodeIds(dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto value) {
        if (datanodeIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatanodeIdsIsMutable();
          datanodeIds_.add(value);
          onChanged();
        } else {
          datanodeIdsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDatanodeIds(
          int index, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto value) {
        if (datanodeIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatanodeIdsIsMutable();
          datanodeIds_.add(index, value);
          onChanged();
        } else {
          datanodeIdsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDatanodeIds(
          dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder builderForValue) {
        if (datanodeIdsBuilder_ == null) {
          ensureDatanodeIdsIsMutable();
          datanodeIds_.add(builderForValue.build());
          onChanged();
        } else {
          datanodeIdsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDatanodeIds(
          int index, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder builderForValue) {
        if (datanodeIdsBuilder_ == null) {
          ensureDatanodeIdsIsMutable();
          datanodeIds_.add(index, builderForValue.build());
          onChanged();
        } else {
          datanodeIdsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDatanodeIds(
          java.lang.Iterable<? extends dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto> values) {
        if (datanodeIdsBuilder_ == null) {
          ensureDatanodeIdsIsMutable();
          super.addAll(values, datanodeIds_);
          onChanged();
        } else {
          datanodeIdsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDatanodeIds() {
        if (datanodeIdsBuilder_ == null) {
          datanodeIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          datanodeIdsBuilder_.clear();
        }
        return this;
      }
      public Builder removeDatanodeIds(int index) {
        if (datanodeIdsBuilder_ == null) {
          ensureDatanodeIdsIsMutable();
          datanodeIds_.remove(index);
          onChanged();
        } else {
          datanodeIdsBuilder_.remove(index);
        }
        return this;
      }
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder getDatanodeIdsBuilder(
          int index) {
        return getDatanodeIdsFieldBuilder().getBuilder(index);
      }
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder getDatanodeIdsOrBuilder(
          int index) {
        if (datanodeIdsBuilder_ == null) {
          return datanodeIds_.get(index);  } else {
          return datanodeIdsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder> 
           getDatanodeIdsOrBuilderList() {
        if (datanodeIdsBuilder_ != null) {
          return datanodeIdsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(datanodeIds_);
        }
      }
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder addDatanodeIdsBuilder() {
        return getDatanodeIdsFieldBuilder().addBuilder(
            dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.getDefaultInstance());
      }
      public dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder addDatanodeIdsBuilder(
          int index) {
        return getDatanodeIdsFieldBuilder().addBuilder(
            index, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.getDefaultInstance());
      }
      public java.util.List<dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder> 
           getDatanodeIdsBuilderList() {
        return getDatanodeIdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder> 
          getDatanodeIdsFieldBuilder() {
        if (datanodeIdsBuilder_ == null) {
          datanodeIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder, dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProtoOrBuilder>(
                  datanodeIds_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          datanodeIds_ = null;
        }
        return datanodeIdsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.objects.DatanodeIdsListProto)
    }
    
    static {
      defaultInstance = new DatanodeIdsListProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.objects.DatanodeIdsListProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_objects_DatanodeIdProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_objects_DatanodeIdProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_objects_DatanodeIdsListProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_objects_DatanodeIdsListProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031DatanodesInfoProtos.proto\022\020protocol.ob" +
      "jects\"%\n\017DatanodeIdProto\022\022\n\ndatanodeId\030\001" +
      " \001(\t\"N\n\024DatanodeIdsListProto\0226\n\013datanode" +
      "Ids\030\001 \003(\0132!.protocol.objects.DatanodeIdP" +
      "rotoB2\n\033dfs.common.protocol.objectsB\023Dat" +
      "anodesInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_objects_DatanodeIdProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_objects_DatanodeIdProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_objects_DatanodeIdProto_descriptor,
              new java.lang.String[] { "DatanodeId", },
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.class,
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdProto.Builder.class);
          internal_static_protocol_objects_DatanodeIdsListProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_objects_DatanodeIdsListProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_objects_DatanodeIdsListProto_descriptor,
              new java.lang.String[] { "DatanodeIds", },
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.class,
              dfs.common.protocol.objects.DatanodesInfoProtos.DatanodeIdsListProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
