// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DatanodeSynchProtos.proto

package dfs.common.protocol.objects;

public final class DatanodeSynchProtos {
  private DatanodeSynchProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegisterDatanodeResponseProtosOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 response = 1;
    boolean hasResponse();
    int getResponse();
  }
  public static final class RegisterDatanodeResponseProtos extends
      com.google.protobuf.GeneratedMessage
      implements RegisterDatanodeResponseProtosOrBuilder {
    // Use RegisterDatanodeResponseProtos.newBuilder() to construct.
    private RegisterDatanodeResponseProtos(Builder builder) {
      super(builder);
    }
    private RegisterDatanodeResponseProtos(boolean noInit) {}
    
    private static final RegisterDatanodeResponseProtos defaultInstance;
    public static RegisterDatanodeResponseProtos getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterDatanodeResponseProtos getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeResponseProtos_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeResponseProtos_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 response = 1;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private int response_;
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResponse() {
      return response_;
    }
    
    private void initFields() {
      response_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, response_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeResponseProtos_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeResponseProtos_fieldAccessorTable;
      }
      
      // Construct using dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        response_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.getDescriptor();
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos getDefaultInstanceForType() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.getDefaultInstance();
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos build() {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos buildPartial() {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos result = new dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.response_ = response_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos) {
          return mergeFrom((dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos other) {
        if (other == dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResponse()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              response_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 response = 1;
      private int response_ ;
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResponse() {
        return response_;
      }
      public Builder setResponse(int value) {
        bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.objects.RegisterDatanodeResponseProtos)
    }
    
    static {
      defaultInstance = new RegisterDatanodeResponseProtos(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.objects.RegisterDatanodeResponseProtos)
  }
  
  public interface RegisterDatanodeParmsProtosOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
  }
  public static final class RegisterDatanodeParmsProtos extends
      com.google.protobuf.GeneratedMessage
      implements RegisterDatanodeParmsProtosOrBuilder {
    // Use RegisterDatanodeParmsProtos.newBuilder() to construct.
    private RegisterDatanodeParmsProtos(Builder builder) {
      super(builder);
    }
    private RegisterDatanodeParmsProtos(boolean noInit) {}
    
    private static final RegisterDatanodeParmsProtos defaultInstance;
    public static RegisterDatanodeParmsProtos getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterDatanodeParmsProtos getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeParmsProtos_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeParmsProtos_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeParmsProtos_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.internal_static_protocol_objects_RegisterDatanodeParmsProtos_fieldAccessorTable;
      }
      
      // Construct using dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.getDescriptor();
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos getDefaultInstanceForType() {
        return dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.getDefaultInstance();
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos build() {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos buildPartial() {
        dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos result = new dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos) {
          return mergeFrom((dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos other) {
        if (other == dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.objects.RegisterDatanodeParmsProtos)
    }
    
    static {
      defaultInstance = new RegisterDatanodeParmsProtos(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.objects.RegisterDatanodeParmsProtos)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_objects_RegisterDatanodeResponseProtos_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_objects_RegisterDatanodeResponseProtos_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_objects_RegisterDatanodeParmsProtos_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_objects_RegisterDatanodeParmsProtos_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031DatanodeSynchProtos.proto\022\020protocol.ob" +
      "jects\"2\n\036RegisterDatanodeResponseProtos\022" +
      "\020\n\010response\030\001 \002(\005\")\n\033RegisterDatanodePar" +
      "msProtos\022\n\n\002id\030\001 \002(\tB2\n\033dfs.common.proto" +
      "col.objectsB\023DatanodeSynchProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_objects_RegisterDatanodeResponseProtos_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_objects_RegisterDatanodeResponseProtos_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_objects_RegisterDatanodeResponseProtos_descriptor,
              new java.lang.String[] { "Response", },
              dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.class,
              dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeResponseProtos.Builder.class);
          internal_static_protocol_objects_RegisterDatanodeParmsProtos_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_objects_RegisterDatanodeParmsProtos_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_objects_RegisterDatanodeParmsProtos_descriptor,
              new java.lang.String[] { "Id", },
              dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.class,
              dfs.common.protocol.objects.DatanodeSynchProtos.RegisterDatanodeParmsProtos.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
